---
sudo: required
dist: trusty
language: python
services:
  - docker
before_script:
  - pip install ansible==$ANSIBLE_VERSION
  - pip install molecule
  - pip install docker-py
script:
  - molecule test
matrix:
  include:
    - env: ANSIBLE_VERSION="2.9.2"
    - env: ANSIBLE_VERSION="2.8.7"
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
