# This file does not run on master nodes
---
- name: Nodes - Check if Certificate Authority is available
  become: yes
  stat:
    path: "{{ i2_pki_path }}/trusted_parent.crt"
  register: trusted_authority

- name: Nodes - Initialize Certificate Directory
  become: yes
  file:
    path: "{{ i2_pki_path }}"
    state: directory
    owner: "{{ i2_user }}"
    group: "{{ i2_group }}"
    mode: 0700

# This command must be run as privileged user or the icinga user
- name: Nodes - Generate Client Ticket on Master
  become: yes
  command: icinga2 pki ticket --cn {{ i2_hostname }}
  register: pki_ticket
  delegate_to: "{{ i2_configuration_master }}"
  when: i2_certificate_signed_by_ca is sameas false

- name: Nodes - Generate self-signed certificate for first-contact with parent
  become: yes
  command: >
    icinga2 pki new-cert --cn {{ i2_hostname }}
      --key {{ i2_pki_path }}/{{ i2_hostname }}.key
      --cert {{ i2_pki_file }}
  when: trusted_authority.stat.exists is sameas false

- name: Nodes - Retrieve Public Certificate from Parent Node
  become: yes
  command: >
    icinga2 pki save-cert
      --key {{ i2_pki_path }}/{{ i2_hostname }}.key
      --cert {{ i2_pki_file }}
      --trustedcert {{ i2_pki_path }}/trusted_parent.crt
      --host {{ hostvars[i2_peer_nodes[0]]['i2_hostname'] }}
  when: trusted_authority.stat.exists is sameas false

- name: Nodes - Retrieve signed certificate and set-up agent (Top-Down)
  become: yes
  command: >
    icinga2 node setup
      --cn {{ i2_hostname }}
      --ticket {{ pki_ticket.stdout }}
      --endpoint {{ hostvars[i2_peer_nodes[0]]['i2_hostname'] }}
      --trustedcert {{ i2_pki_path }}/trusted_parent.crt
      --zone {{ i2_zonename }}
      --parent_zone {{ i2_zone }}
      --parent_host {{ hostvars[i2_peer_nodes[0]]['i2_hostname'] }}
      --accept-commands
      --accept-config
      --disable-confd
  when: i2_connection_direction == 'top-down' and not i2_certificate_signed_by_ca
  notify: restart icinga2

- name: Collect endpoints for bottom-up config
  set_fact:
    endpoints: "{{ endpoints|default('') }}
     --endpoint {{ hostvars[item]['i2_hostname'] }},{{ hostvars[item]['i2_api_host'] }},{{ hostvars[item]['i2_api_port'] }}"
  loop: "{{ i2_peer_nodes }}"
  when: i2_connection_direction == 'bottom-up' and not i2_certificate_signed_by_ca

- name: Nodes - Retrieve signed certificate and set-up agent (Bottom-Up)
  become: yes
  command: >
    icinga2 node setup
      --cn {{ i2_hostname }}
      --ticket {{ pki_ticket.stdout }} {{ endpoints }}
      --trustedcert {{ i2_pki_path }}/trusted_parent.crt
      --zone {{ i2_zonename }}
      --parent_zone {{ i2_zone }}
      --parent_host {{ hostvars[i2_peer_nodes[0]]['i2_hostname'] }}
      --accept-commands
      --accept-config
      --disable-confd
  when:
    - i2_connection_direction == 'bottom-up'
    - not i2_certificate_signed_by_ca
    - endpoints is defined
  notify: restart icinga2
