---
- include_tasks: icinga2-web2-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: icinga2-web2-Debian.yml
  when: ansible_os_family == 'Debian'

- name: IcingaWeb2 - Include default config for module
  set_fact:
    i2_webui_default_config: "{{ i2_webui_default_config|combine(
      i2_webui_default_module_config[item]|default({}), recursive=True)
    }}"
  loop: "{{ i2_webui_modules | map(attribute='name') | list  }}"

- name: IcingaWeb2 – Create configuration directories
  file:
    path: "/etc/icingaweb2/{{ item }}"
    owner: "{{ i2_webui_user }}"
    group: "{{ i2_webui_group }}"
    mode: 02770
    state: directory
  loop: "{{ default | union(additional) }}"
  vars:
    default:
      - ""
      - "modules"
      - "modules/monitoring"
      - "modules/translation"
      - "modules/director"
      - "enabledModules"
    additional: "{{ i2_webui_config | json_query('*.file') | map('dirname') | list | unique }}"

- name: IcingaWeb2 - Create configuration files
  become: true
  template:
    src: "icingaweb2-config.ini.j2"
    dest: "/etc/icingaweb2/{{ item.value.file }}"
    mode: 0660
    owner: "{{ i2_webui_user }}"
    group: "{{ i2_webui_group }}"
  loop: "{{ i2_webui_config | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: IcingaWeb2 - Enable modules
  become: true
  file:
    src: '/usr/share/icingaweb2/modules/{{ item }}'
    dest: '/etc/icingaweb2/enabledModules/{{ item }}'
    owner: "{{ i2_webui_user }}"
    group: "{{ i2_webui_group }}"
    state: link
  loop:
    - doc
    - monitoring

- name: Check if IcingaWeb2 configuration is in place
  become: yes
  stat:
    path: /etc/icingaweb2/config.ini
  register: icingawebconfig
  tags: token

- name: Create setup token and display setup token
  when: not icingawebconfig.stat.exists
  tags: token
  block:
  - name: Create setup token
    become: yes
    command: icingacli setup token create
    args:
      creates: /etc/icingaweb2/setup.token

  - name: Get setup token
    become: yes
    shell: 'icingacli setup token show | sed "s/.*token is: \(.*\)/\1/g"'
    changed_when: no
    register: setup_token

  - name: IcingaWeb2 Installation finished
    debug:
      msg: >-
        The WebUI token is {{ setup_token.stdout }},
        use it at http://{{ i2_hostname }}/icingaweb2/setup
        ({{ ansible_facts.default_ipv4.address }}) to continue the installation
    tags: icinga2-ansible-web2-ui-install

- name: IcingaWeb2 – Install additional modules
  import_tasks: icinga2-web2-modules.yml
