---
- name: Include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Boostrap defaults
  import_tasks: icinga2-bootstrap.yml
  tags:
    - always

- name: Set up Icinga Repositories and install packages
  import_tasks: icinga2.yml
  tags:
    - install

- name: Set up Icinga2 masters
  when: i2_master
  block:
  - name: Setup distibuted layer
    import_tasks: icinga2-layer.yml

- meta: flush_handlers

- name: Set up Icinga2 satellites
  when: i2_satellite
  block:
  - name: Setup distibuted layer
    import_tasks: icinga2-layer.yml

- meta: flush_handlers

- name: Set up Icinga2 agents
  when: not i2_master and not i2_satellite
  block:
  - name: Setup distibuted layer
    import_tasks: icinga2-layer.yml

- meta: flush_handlers

- name: Set up Icinga Templates, Objects and Apply Rules
  import_tasks: icinga2-objects.yml
  when: inventory_hostname == i2_configuration_master
  tags:
    - objects

- name: Copy any custom check scripts or plugins in place
  import_tasks: icinga2-scripts.yml
  when: i2_custom_scripts|length
  tags:
    - plugins

- name: Make sure Icinga 2 is started
  service:
    name: icinga2
    state: started
    enabled: yes
  when: i2_manage_service

- name: Set up Icingaweb2
  import_tasks: icinga2-web2.yml
  when:
    - inventory_hostname == i2_configuration_master
    - i2_setup_webui
  tags:
    - webui
